WARNING 2018-04-21 04:22:19,120 base 67976 123145343856640 Not Found: /favicon.ico
WARNING 2018-04-21 04:22:32,634 base 67976 123145343856640 Not Found: /favicon.ico
WARNING 2018-04-21 04:23:38,880 base 67976 123145343856640 Not Found: /favicon.ico
WARNING 2018-04-21 04:24:55,291 base 67976 123145343856640 Not Found: /favicon.ico
WARNING 2018-04-21 04:25:38,643 base 67976 123145343856640 Not Found: /favicon.ico
WARNING 2018-04-21 04:29:13,771 base 67976 123145343856640 Not Found: /favicon.ico
WARNING 2018-04-21 04:29:44,796 base 67976 123145343856640 Not Found: /favicon.ico
WARNING 2018-04-21 04:29:59,243 base 67976 123145343856640 Not Found: /favicon.ico
WARNING 2018-04-21 04:49:48,250 base 67976 123145343856640 Not Found: /favicon.ico
WARNING 2018-04-21 04:50:29,248 base 67976 123145343856640 Not Found: /favicon.ico
WARNING 2018-04-21 04:50:41,645 base 67976 123145343856640 Not Found: /favicon.ico
WARNING 2018-04-21 04:51:27,799 base 67976 123145343856640 Not Found: /favicon.ico
WARNING 2018-04-21 05:52:08,493 base 68802 123145395974144 Not Found: /login/
WARNING 2018-04-21 05:52:08,601 base 68802 123145400180736 Not Found: /favicon.ico
WARNING 2018-04-21 05:52:11,079 base 68802 123145404387328 Not Found: /login/
ERROR 2018-04-21 05:52:14,036 exception 68802 123145395974144 Internal Server Error: /login
Traceback (most recent call last):
  File "/Users/K2A/GIT/marlo/env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/K2A/GIT/marlo/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/Users/K2A/GIT/marlo/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/K2A/GIT/marlo/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: login() takes at least 2 arguments (1 given)
WARNING 2018-04-21 05:53:44,564 base 68823 123145423966208 Not Found: /favicon.ico
ERROR 2018-04-21 06:01:21,259 exception 68823 123145423966208 Internal Server Error: /login
Traceback (most recent call last):
  File "/Users/K2A/GIT/marlo/env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/K2A/GIT/marlo/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/Users/K2A/GIT/marlo/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/K2A/GIT/marlo/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/K2A/GIT/marlo/webapp/core/views.py", line 28, in login_user
    return render(request, 'login.html')
  File "/Users/K2A/GIT/marlo/env/lib/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/K2A/GIT/marlo/env/lib/python2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/K2A/GIT/marlo/env/lib/python2.7/site-packages/django/template/loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "/Users/K2A/GIT/marlo/env/lib/python2.7/site-packages/django/template/backends/django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/K2A/GIT/marlo/env/lib/python2.7/site-packages/django/template/engine.py", line 162, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/K2A/GIT/marlo/env/lib/python2.7/site-packages/django/template/engine.py", line 136, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/Users/K2A/GIT/marlo/env/lib/python2.7/site-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/K2A/GIT/marlo/env/lib/python2.7/site-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/K2A/GIT/marlo/env/lib/python2.7/site-packages/django/template/base.py", line 230, in compile_nodelist
    return parser.parse()
  File "/Users/K2A/GIT/marlo/env/lib/python2.7/site-packages/django/template/base.py", line 515, in parse
    raise self.error(token, e)
TemplateSyntaxError: Invalid block tag on line 133: 'static', expected 'endblock'. Did you forget to register or load this tag?
WARNING 2018-04-21 06:01:22,416 base 68823 123145428172800 Not Found: /favicon.ico
ERROR 2018-04-21 06:02:52,103 exception 68823 123145423966208 Internal Server Error: /login
Traceback (most recent call last):
  File "/Users/K2A/GIT/marlo/env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/K2A/GIT/marlo/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/Users/K2A/GIT/marlo/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/K2A/GIT/marlo/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/K2A/GIT/marlo/webapp/core/views.py", line 28, in login_user
    return render(request, 'login.html')
  File "/Users/K2A/GIT/marlo/env/lib/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/K2A/GIT/marlo/env/lib/python2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/K2A/GIT/marlo/env/lib/python2.7/site-packages/django/template/loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "/Users/K2A/GIT/marlo/env/lib/python2.7/site-packages/django/template/backends/django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/K2A/GIT/marlo/env/lib/python2.7/site-packages/django/template/engine.py", line 162, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/K2A/GIT/marlo/env/lib/python2.7/site-packages/django/template/engine.py", line 136, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/Users/K2A/GIT/marlo/env/lib/python2.7/site-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/K2A/GIT/marlo/env/lib/python2.7/site-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/K2A/GIT/marlo/env/lib/python2.7/site-packages/django/template/base.py", line 230, in compile_nodelist
    return parser.parse()
  File "/Users/K2A/GIT/marlo/env/lib/python2.7/site-packages/django/template/base.py", line 515, in parse
    raise self.error(token, e)
TemplateSyntaxError: Invalid block tag on line 125: 'static', expected 'endblock'. Did you forget to register or load this tag?
WARNING 2018-04-21 06:02:53,101 base 68823 123145428172800 Not Found: /favicon.ico
WARNING 2018-04-21 06:03:34,231 base 68823 123145423966208 Not Found: /favicon.ico
WARNING 2018-04-21 06:04:44,971 base 68823 123145423966208 Not Found: /favicon.ico
WARNING 2018-04-21 06:05:02,000 base 68823 123145423966208 Not Found: /favicon.ico
WARNING 2018-04-21 06:06:35,151 base 68823 123145423966208 Not Found: /favicon.ico
WARNING 2018-04-21 06:07:40,410 base 68823 123145423966208 Not Found: /favicon.ico
WARNING 2018-04-21 06:37:52,642 csrf 68823 123145423966208 Forbidden (CSRF token missing or incorrect.): /login
WARNING 2018-04-21 08:34:47,667 base 69896 123145561186304 Not Found: /favicon.ico
WARNING 2018-04-21 08:36:30,308 base 69896 123145561186304 Not Found: /favicon.ico
WARNING 2018-04-21 08:42:00,090 base 69991 123145364393984 Not Found: /favicon.ico
WARNING 2018-04-21 08:44:10,120 base 69991 123145364393984 Not Found: /favicon.ico
WARNING 2018-04-21 08:44:17,112 base 69991 123145364393984 Not Found: /favicon.ico
WARNING 2018-04-21 08:44:33,164 base 69991 123145364393984 Not Found: /favicon.ico
WARNING 2018-04-21 08:44:55,559 base 69991 123145364393984 Not Found: /favicon.ico
ERROR 2018-04-21 08:45:02,822 exception 69991 123145364393984 Internal Server Error: /logout
Traceback (most recent call last):
  File "/Users/K2A/GIT/marlo/env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/K2A/GIT/marlo/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/Users/K2A/GIT/marlo/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/K2A/GIT/marlo/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/K2A/GIT/marlo/webapp/core/views.py", line 40, in logout_user
    return HttpResponseRedirect(reverse('login'))
  File "/Users/K2A/GIT/marlo/env/lib/python2.7/site-packages/django/urls/base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/Users/K2A/GIT/marlo/env/lib/python2.7/site-packages/django/urls/resolvers.py", line 497, in _reverse_with_prefix
    raise NoReverseMatch(msg)
NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
WARNING 2018-04-21 08:46:05,675 base 70073 123145502187520 Not Found: /favicon.ico
WARNING 2018-04-21 08:47:28,486 base 70103 123145396613120 Not Found: /favicon.ico
ERROR 2018-04-21 08:47:33,465 exception 70103 123145396613120 Internal Server Error: /dashboard
Traceback (most recent call last):
  File "/Users/K2A/GIT/marlo/env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/K2A/GIT/marlo/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/Users/K2A/GIT/marlo/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/K2A/GIT/marlo/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/K2A/GIT/marlo/env/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 25, in _wrapped_view
    resolved_login_url = resolve_url(login_url or settings.LOGIN_URL)
  File "/Users/K2A/GIT/marlo/env/lib/python2.7/site-packages/django/shortcuts.py", line 147, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "/Users/K2A/GIT/marlo/env/lib/python2.7/site-packages/django/urls/base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/Users/K2A/GIT/marlo/env/lib/python2.7/site-packages/django/urls/resolvers.py", line 497, in _reverse_with_prefix
    raise NoReverseMatch(msg)
NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
WARNING 2018-04-21 08:47:47,171 base 70110 123145350762496 Not Found: /favicon.ico
WARNING 2018-04-21 09:45:13,824 base 70660 123145446805504 Not Found: /favicon.ico
